language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python api/api.py
  - http POST :5000/api/businesses/ business_name='jpcom ltd' business_type="IT" business_desc='Information Technology'